[tool.setuptools]
packages = ["routing_packager_app"]

[project]
name = "routing-graph-packager"
version = "1.1.0"
description = "Backend to generate packages of routing graphs for FOSS routing engines in a job queue."
authors = [
 { name = "Nils Nolde", email = "nils@gis-ops.com" },
 { name = "Christian Beiwinkel", email = "chrstn@bwnkl.de" },
]
license = "MIT"
requires-python = ">= 3.12"
dependencies = [
    "anyio>=4.14.2",
    "arq>=0.28.0",
    "bump-pydantic>=0.8.0",
    "croniter>=6.2.4",
    "datadog>=0.53.0",
    "fastapi>=0.141.1",
    "geoalchemy2>=0.20.0",
    "gunicorn>=26.2.0",
    "osmium>=4.3.1",
    "passlib>=1.7.4",
    "prometheus-client>=0.23.1",
    "psycopg2-binary>=2.9.12",
    "pydantic[email]>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "redis>=5.3.1",
    "requests>=2.34.2",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0.52",
    "sqlalchemy-utils>=0.42.1",
    "sqlmodel>=0.0.42",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "coverage>=7.16.0",
    "coveralls>=4.1.0",
    "httpx>=0.28.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.5",
]

[tool.ruff]

extend-exclude = [".venv", "third_party", "build"]
lint.preview = true

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
lint.select = ["E", "F", "RUF022"]
lint.ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "I",
  "N",
  "Q",
  "S",
  "T",
  "W",
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "DJ",
  "DTZ",
  "EM",
  "ERA",
  "EXE",
  "FBT",
  "ICN",
  "INP",
  "ISC",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "TCH",
  "TID",
  "TRY",
  "UP",
  "YTT",
  "RUF022",
]
lint.unfixable = []
format.preview = true
line-length = 105

