name: Deploy -> int
  
on:
  #workflow_run:
  #  workflows: ["publish"]
  #  types:
  #    - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: integration_runner
    environment: integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker compose version

      - name: Generate .docker_env file
        run: |
          cat > .docker_env <<EOF
          POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
          SMTP_HOST=${{ vars.SMTP_HOST }}
          REDIS_URL=${{ vars.REDIS_URL }}
          ADMIN_EMAIL=${{ vars.ADMIN_EMAIL }}
          ADMIN_PASS=${{ secrets.ADMIN_PASS }}
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
          POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}
          SSL_CERT=${{ vars.SSL_CERT }}
          SSL_KEY=${{ vars.SSL_KEY }}
          CONCURRENCY=${{ vars.CONCURRENCY }}
          MAX_CACHE_SIZE=${{ vars.MAX_CACHE_SIZE }}
          USE_ELEVATION=${{ vars.USE_ELEVATION }}
          PBF_LOCAL_PATH=${{ vars.PBF_LOCAL_PATH }}
          PBF_URL=${{ vars.PBF_URL }}
          GRAPH_BUILD_CRON=${{ vars.GRAPH_BUILD_CRON || '0 3 * * 0' }}
          GRAPH_PRUNE_TIMEOUT=${{ vars.GRAPH_PRUNE_TIMEOUT || '3600' }}
          GRAPH_LOCK_TTL=${{ vars.GRAPH_LOCK_TTL || '345600' }}
          STATSD_HOST=statsd-exporter
          GF_SECURITY_ADMIN_USER=${{ vars.GRAFANA_ADMIN_USER || 'admin' }}
          GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASS }}
          HTTP_PROXY=${{ vars.HTTP_PROXY }}
          HTTPS_PROXY=${{ vars.HTTPS_PROXY }}
          NO_PROXY=${{ vars.NO_PROXY }}
          EOF

          cat > .env <<EOF
          DATA_DIR=${{ vars.DATA_DIR }}
          TMP_DATA_DIR=${{ vars.TMP_DATA_DIR }}
          COMPOSE_PROJECT_NAME=${{ vars.COMPOSE_PROJECT_NAME }}
          SSL_CERT_DIR=${{ vars.SSL_CERT_DIR }}
          DOCKER_HOST=unix:///var/run/docker.sock
          EOF

      - name: Pull latest images
        run: |
          docker compose --profile monitoring pull

      - name: Deploy app
        run: |
          docker compose --profile monitoring down --remove-orphans
          docker compose --profile monitoring up -d --build --remove-orphans
          docker image prune -af
