name: Update Docker & Compose

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: integration_runner
    environment: integration
    steps:
      - name: Update Docker
        run: |
          serviceswitch
          export HTTPS_PROXY=http://prxp01.admin.ch:8080

          # Stop / delete containers if there are
          running=$(docker ps -q)
          if [ -n "$running" ]; then
            docker stop $running
          fi

          all=$(docker ps -a -q)
          if [ -n "$all" ]; then
            docker rm $all
          fi

          docker image prune -f
          systemctl --user stop docker
          rm -f /prog/kadas/bin/dockerd
          curl -fsSL https://get.docker.com/rootless | sh
          docker version

      - name: Update Docker Compose
        run: |
          PLUGIN_DIR="$HOME/.docker/cli-plugins"

          # if plugin folder exists, empty it otherwise create.
          if [ -d "$PLUGIN_DIR" ]; then
            rm -rf "$PLUGIN_DIR"/*
          else
            mkdir -p "$PLUGIN_DIR"
          fi

          curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
            -o "$PLUGIN_DIR/docker-compose"
          chmod +x "$PLUGIN_DIR/docker-compose"
          docker compose version

      - name: Start runner
        run: |
          cd ~/src/mgdi-runner
          docker compose up -d
